// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/wallet.proto

package walletpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{0}
}

type WalletInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         string                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"` // ETH / TRX
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"` // 一般生产环境不建议返回
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletInfo) Reset() {
	*x = WalletInfo{}
	mi := &file_proto_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletInfo) ProtoMessage() {}

func (x *WalletInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletInfo.ProtoReflect.Descriptor instead.
func (*WalletInfo) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *WalletInfo) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *WalletInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WalletInfo) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *WalletInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type MemberReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      int64                  `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberReq) Reset() {
	*x = MemberReq{}
	mi := &file_proto_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberReq) ProtoMessage() {}

func (x *MemberReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberReq.ProtoReflect.Descriptor instead.
func (*MemberReq) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *MemberReq) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

type CreateWalletReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      int64                  `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletReq) Reset() {
	*x = CreateWalletReq{}
	mi := &file_proto_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletReq) ProtoMessage() {}

func (x *CreateWalletReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletReq.ProtoReflect.Descriptor instead.
func (*CreateWalletReq) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWalletReq) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

type TransferReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         string                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"` // ETH / TRX
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // ERC20 / TRC20 / ETH / TRX
	From          string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"` // 建议字符串，避免精度问题
	PrivateKey    string                 `protobuf:"bytes,6,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferReq) Reset() {
	*x = TransferReq{}
	mi := &file_proto_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferReq) ProtoMessage() {}

func (x *TransferReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferReq.ProtoReflect.Descriptor instead.
func (*TransferReq) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *TransferReq) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *TransferReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TransferReq) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TransferReq) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TransferReq) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TransferReq) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type EstimateGasReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         string                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	From          string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateGasReq) Reset() {
	*x = EstimateGasReq{}
	mi := &file_proto_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateGasReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateGasReq) ProtoMessage() {}

func (x *EstimateGasReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateGasReq.ProtoReflect.Descriptor instead.
func (*EstimateGasReq) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *EstimateGasReq) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *EstimateGasReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EstimateGasReq) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *EstimateGasReq) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *EstimateGasReq) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type UniqueIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UniqueId      int64                  `protobuf:"varint,1,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniqueIdResp) Reset() {
	*x = UniqueIdResp{}
	mi := &file_proto_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniqueIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueIdResp) ProtoMessage() {}

func (x *UniqueIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueIdResp.ProtoReflect.Descriptor instead.
func (*UniqueIdResp) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *UniqueIdResp) GetUniqueId() int64 {
	if x != nil {
		return x.UniqueId
	}
	return 0
}

type CreateWalletResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Wallet        *WalletInfo            `protobuf:"bytes,2,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletResp) Reset() {
	*x = CreateWalletResp{}
	mi := &file_proto_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletResp) ProtoMessage() {}

func (x *CreateWalletResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletResp.ProtoReflect.Descriptor instead.
func (*CreateWalletResp) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *CreateWalletResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateWalletResp) GetWallet() *WalletInfo {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type WalletResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *WalletInfo            `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletResp) Reset() {
	*x = WalletResp{}
	mi := &file_proto_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletResp) ProtoMessage() {}

func (x *WalletResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletResp.ProtoReflect.Descriptor instead.
func (*WalletResp) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *WalletResp) GetWallet() *WalletInfo {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type WalletListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallets       []*WalletInfo          `protobuf:"bytes,1,rep,name=wallets,proto3" json:"wallets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletListResp) Reset() {
	*x = WalletListResp{}
	mi := &file_proto_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletListResp) ProtoMessage() {}

func (x *WalletListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletListResp.ProtoReflect.Descriptor instead.
func (*WalletListResp) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *WalletListResp) GetWallets() []*WalletInfo {
	if x != nil {
		return x.Wallets
	}
	return nil
}

type EstimateGasResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GasFee        string                 `protobuf:"bytes,1,opt,name=gas_fee,json=gasFee,proto3" json:"gas_fee,omitempty"`
	Unit          string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"` // ETH / TRX
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateGasResp) Reset() {
	*x = EstimateGasResp{}
	mi := &file_proto_wallet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateGasResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateGasResp) ProtoMessage() {}

func (x *EstimateGasResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateGasResp.ProtoReflect.Descriptor instead.
func (*EstimateGasResp) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{10}
}

func (x *EstimateGasResp) GetGasFee() string {
	if x != nil {
		return x.GasFee
	}
	return ""
}

func (x *EstimateGasResp) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type TransferResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TxHash        string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResp) Reset() {
	*x = TransferResp{}
	mi := &file_proto_wallet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResp) ProtoMessage() {}

func (x *TransferResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResp.ProtoReflect.Descriptor instead.
func (*TransferResp) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{11}
}

func (x *TransferResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferResp) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TransferResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"` // 会员ID
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`                       // 链类型: ETH / TRX
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                       // 币种: ETH / TRX / USDT 等（或合约地址）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_proto_wallet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{12}
}

func (x *GetBalanceRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *GetBalanceRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *GetBalanceRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Balance       string                 `protobuf:"bytes,4,opt,name=balance,proto3" json:"balance,omitempty"`    // 余额（字符串防止精度丢失）
	Decimals      int32                  `protobuf:"varint,5,opt,name=decimals,proto3" json:"decimals,omitempty"` // 精度（比如 ETH 18）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_proto_wallet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{13}
}

func (x *GetBalanceResponse) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *GetBalanceResponse) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *GetBalanceResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetBalanceResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *GetBalanceResponse) GetDecimals() int32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

var File_proto_wallet_proto protoreflect.FileDescriptor

const file_proto_wallet_proto_rawDesc = "" +
	"\n" +
	"\x12proto/wallet.proto\x12\x06wallet\"\a\n" +
	"\x05Empty\"|\n" +
	"\n" +
	"WalletInfo\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\tR\n" +
	"privateKey\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"(\n" +
	"\tMemberReq\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\x03R\bmemberId\".\n" +
	"\x0fCreateWalletReq\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\x03R\bmemberId\"\x96\x01\n" +
	"\vTransferReq\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1f\n" +
	"\vprivate_key\x18\x06 \x01(\tR\n" +
	"privateKey\"x\n" +
	"\x0eEstimateGasReq\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\"+\n" +
	"\fUniqueIdResp\x12\x1b\n" +
	"\tunique_id\x18\x01 \x01(\x03R\buniqueId\"X\n" +
	"\x10CreateWalletResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12*\n" +
	"\x06wallet\x18\x02 \x01(\v2\x12.wallet.WalletInfoR\x06wallet\"8\n" +
	"\n" +
	"WalletResp\x12*\n" +
	"\x06wallet\x18\x01 \x01(\v2\x12.wallet.WalletInfoR\x06wallet\">\n" +
	"\x0eWalletListResp\x12,\n" +
	"\awallets\x18\x01 \x03(\v2\x12.wallet.WalletInfoR\awallets\">\n" +
	"\x0fEstimateGasResp\x12\x17\n" +
	"\agas_fee\x18\x01 \x01(\tR\x06gasFee\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\"W\n" +
	"\fTransferResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\\\n" +
	"\x11GetBalanceRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\x93\x01\n" +
	"\x12GetBalanceResponse\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x18\n" +
	"\abalance\x18\x04 \x01(\tR\abalance\x12\x1a\n" +
	"\bdecimals\x18\x05 \x01(\x05R\bdecimals2\xa9\x05\n" +
	"\rWalletService\x122\n" +
	"\vGetUniqueId\x12\r.wallet.Empty\x1a\x14.wallet.UniqueIdResp\x12E\n" +
	"\x10CreateUserWallet\x12\x17.wallet.CreateWalletReq\x1a\x18.wallet.CreateWalletResp\x127\n" +
	"\n" +
	"ListWallet\x12\x11.wallet.MemberReq\x1a\x16.wallet.WalletListResp\x125\n" +
	"\fGetETHWallet\x12\x11.wallet.MemberReq\x1a\x12.wallet.WalletResp\x125\n" +
	"\fGetTRXWallet\x12\x11.wallet.MemberReq\x1a\x12.wallet.WalletResp\x12;\n" +
	"\x0eTransferCrypto\x12\x13.wallet.TransferReq\x1a\x14.wallet.TransferResp\x12>\n" +
	"\vEstimateGas\x12\x16.wallet.EstimateGasReq\x1a\x17.wallet.EstimateGasResp\x127\n" +
	"\x12GetReconcileWallet\x12\r.wallet.Empty\x1a\x12.wallet.WalletResp\x12<\n" +
	"\x0fTestTransferETH\x12\x13.wallet.TransferReq\x1a\x14.wallet.TransferResp\x12=\n" +
	"\x10TestTransferTRON\x12\x13.wallet.TransferReq\x1a\x14.wallet.TransferResp\x12C\n" +
	"\n" +
	"GetBalance\x12\x19.wallet.GetBalanceRequest\x1a\x1a.wallet.GetBalanceResponseB\"Z pkg/walletgrpc/walletpb;walletpbb\x06proto3"

var (
	file_proto_wallet_proto_rawDescOnce sync.Once
	file_proto_wallet_proto_rawDescData []byte
)

func file_proto_wallet_proto_rawDescGZIP() []byte {
	file_proto_wallet_proto_rawDescOnce.Do(func() {
		file_proto_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wallet_proto_rawDesc), len(file_proto_wallet_proto_rawDesc)))
	})
	return file_proto_wallet_proto_rawDescData
}

var file_proto_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_wallet_proto_goTypes = []any{
	(*Empty)(nil),              // 0: wallet.Empty
	(*WalletInfo)(nil),         // 1: wallet.WalletInfo
	(*MemberReq)(nil),          // 2: wallet.MemberReq
	(*CreateWalletReq)(nil),    // 3: wallet.CreateWalletReq
	(*TransferReq)(nil),        // 4: wallet.TransferReq
	(*EstimateGasReq)(nil),     // 5: wallet.EstimateGasReq
	(*UniqueIdResp)(nil),       // 6: wallet.UniqueIdResp
	(*CreateWalletResp)(nil),   // 7: wallet.CreateWalletResp
	(*WalletResp)(nil),         // 8: wallet.WalletResp
	(*WalletListResp)(nil),     // 9: wallet.WalletListResp
	(*EstimateGasResp)(nil),    // 10: wallet.EstimateGasResp
	(*TransferResp)(nil),       // 11: wallet.TransferResp
	(*GetBalanceRequest)(nil),  // 12: wallet.GetBalanceRequest
	(*GetBalanceResponse)(nil), // 13: wallet.GetBalanceResponse
}
var file_proto_wallet_proto_depIdxs = []int32{
	1,  // 0: wallet.CreateWalletResp.wallet:type_name -> wallet.WalletInfo
	1,  // 1: wallet.WalletResp.wallet:type_name -> wallet.WalletInfo
	1,  // 2: wallet.WalletListResp.wallets:type_name -> wallet.WalletInfo
	0,  // 3: wallet.WalletService.GetUniqueId:input_type -> wallet.Empty
	3,  // 4: wallet.WalletService.CreateUserWallet:input_type -> wallet.CreateWalletReq
	2,  // 5: wallet.WalletService.ListWallet:input_type -> wallet.MemberReq
	2,  // 6: wallet.WalletService.GetETHWallet:input_type -> wallet.MemberReq
	2,  // 7: wallet.WalletService.GetTRXWallet:input_type -> wallet.MemberReq
	4,  // 8: wallet.WalletService.TransferCrypto:input_type -> wallet.TransferReq
	5,  // 9: wallet.WalletService.EstimateGas:input_type -> wallet.EstimateGasReq
	0,  // 10: wallet.WalletService.GetReconcileWallet:input_type -> wallet.Empty
	4,  // 11: wallet.WalletService.TestTransferETH:input_type -> wallet.TransferReq
	4,  // 12: wallet.WalletService.TestTransferTRON:input_type -> wallet.TransferReq
	12, // 13: wallet.WalletService.GetBalance:input_type -> wallet.GetBalanceRequest
	6,  // 14: wallet.WalletService.GetUniqueId:output_type -> wallet.UniqueIdResp
	7,  // 15: wallet.WalletService.CreateUserWallet:output_type -> wallet.CreateWalletResp
	9,  // 16: wallet.WalletService.ListWallet:output_type -> wallet.WalletListResp
	8,  // 17: wallet.WalletService.GetETHWallet:output_type -> wallet.WalletResp
	8,  // 18: wallet.WalletService.GetTRXWallet:output_type -> wallet.WalletResp
	11, // 19: wallet.WalletService.TransferCrypto:output_type -> wallet.TransferResp
	10, // 20: wallet.WalletService.EstimateGas:output_type -> wallet.EstimateGasResp
	8,  // 21: wallet.WalletService.GetReconcileWallet:output_type -> wallet.WalletResp
	11, // 22: wallet.WalletService.TestTransferETH:output_type -> wallet.TransferResp
	11, // 23: wallet.WalletService.TestTransferTRON:output_type -> wallet.TransferResp
	13, // 24: wallet.WalletService.GetBalance:output_type -> wallet.GetBalanceResponse
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_wallet_proto_init() }
func file_proto_wallet_proto_init() {
	if File_proto_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wallet_proto_rawDesc), len(file_proto_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wallet_proto_goTypes,
		DependencyIndexes: file_proto_wallet_proto_depIdxs,
		MessageInfos:      file_proto_wallet_proto_msgTypes,
	}.Build()
	File_proto_wallet_proto = out.File
	file_proto_wallet_proto_goTypes = nil
	file_proto_wallet_proto_depIdxs = nil
}
