// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/wallet.proto

package walletpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalletService_GetUniqueId_FullMethodName        = "/wallet.WalletService/GetUniqueId"
	WalletService_CreateUserWallet_FullMethodName   = "/wallet.WalletService/CreateUserWallet"
	WalletService_ListWallet_FullMethodName         = "/wallet.WalletService/ListWallet"
	WalletService_GetETHWallet_FullMethodName       = "/wallet.WalletService/GetETHWallet"
	WalletService_GetTRXWallet_FullMethodName       = "/wallet.WalletService/GetTRXWallet"
	WalletService_TransferCrypto_FullMethodName     = "/wallet.WalletService/TransferCrypto"
	WalletService_EstimateGas_FullMethodName        = "/wallet.WalletService/EstimateGas"
	WalletService_GetReconcileWallet_FullMethodName = "/wallet.WalletService/GetReconcileWallet"
	WalletService_TestTransferETH_FullMethodName    = "/wallet.WalletService/TestTransferETH"
	WalletService_TestTransferTRON_FullMethodName   = "/wallet.WalletService/TestTransferTRON"
	WalletService_GetBalance_FullMethodName         = "/wallet.WalletService/GetBalance"
)

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletServiceClient interface {
	// 获取唯一ID
	GetUniqueId(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UniqueIdResp, error)
	// 创建用户钱包
	CreateUserWallet(ctx context.Context, in *CreateWalletReq, opts ...grpc.CallOption) (*CreateWalletResp, error)
	// 获取用户所有钱包
	ListWallet(ctx context.Context, in *MemberReq, opts ...grpc.CallOption) (*WalletListResp, error)
	// 获取用户 ETH 地址
	GetETHWallet(ctx context.Context, in *MemberReq, opts ...grpc.CallOption) (*WalletResp, error)
	// 获取用户 TRX 地址
	GetTRXWallet(ctx context.Context, in *MemberReq, opts ...grpc.CallOption) (*WalletResp, error)
	// 转账（支持 ERC20 / TRC20）
	TransferCrypto(ctx context.Context, in *TransferReq, opts ...grpc.CallOption) (*TransferResp, error)
	// 预估手续费
	EstimateGas(ctx context.Context, in *EstimateGasReq, opts ...grpc.CallOption) (*EstimateGasResp, error)
	// 获取对账钱包
	GetReconcileWallet(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WalletResp, error)
	// 测试ETH转账
	TestTransferETH(ctx context.Context, in *TransferReq, opts ...grpc.CallOption) (*TransferResp, error)
	// 测试TRON转账
	TestTransferTRON(ctx context.Context, in *TransferReq, opts ...grpc.CallOption) (*TransferResp, error)
	// 查询余额
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
}

type walletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServiceClient(cc grpc.ClientConnInterface) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) GetUniqueId(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UniqueIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UniqueIdResp)
	err := c.cc.Invoke(ctx, WalletService_GetUniqueId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) CreateUserWallet(ctx context.Context, in *CreateWalletReq, opts ...grpc.CallOption) (*CreateWalletResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWalletResp)
	err := c.cc.Invoke(ctx, WalletService_CreateUserWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ListWallet(ctx context.Context, in *MemberReq, opts ...grpc.CallOption) (*WalletListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletListResp)
	err := c.cc.Invoke(ctx, WalletService_ListWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetETHWallet(ctx context.Context, in *MemberReq, opts ...grpc.CallOption) (*WalletResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletResp)
	err := c.cc.Invoke(ctx, WalletService_GetETHWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetTRXWallet(ctx context.Context, in *MemberReq, opts ...grpc.CallOption) (*WalletResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletResp)
	err := c.cc.Invoke(ctx, WalletService_GetTRXWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) TransferCrypto(ctx context.Context, in *TransferReq, opts ...grpc.CallOption) (*TransferResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResp)
	err := c.cc.Invoke(ctx, WalletService_TransferCrypto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) EstimateGas(ctx context.Context, in *EstimateGasReq, opts ...grpc.CallOption) (*EstimateGasResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EstimateGasResp)
	err := c.cc.Invoke(ctx, WalletService_EstimateGas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetReconcileWallet(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WalletResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletResp)
	err := c.cc.Invoke(ctx, WalletService_GetReconcileWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) TestTransferETH(ctx context.Context, in *TransferReq, opts ...grpc.CallOption) (*TransferResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResp)
	err := c.cc.Invoke(ctx, WalletService_TestTransferETH_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) TestTransferTRON(ctx context.Context, in *TransferReq, opts ...grpc.CallOption) (*TransferResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResp)
	err := c.cc.Invoke(ctx, WalletService_TestTransferTRON_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, WalletService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
// All implementations must embed UnimplementedWalletServiceServer
// for forward compatibility.
type WalletServiceServer interface {
	// 获取唯一ID
	GetUniqueId(context.Context, *Empty) (*UniqueIdResp, error)
	// 创建用户钱包
	CreateUserWallet(context.Context, *CreateWalletReq) (*CreateWalletResp, error)
	// 获取用户所有钱包
	ListWallet(context.Context, *MemberReq) (*WalletListResp, error)
	// 获取用户 ETH 地址
	GetETHWallet(context.Context, *MemberReq) (*WalletResp, error)
	// 获取用户 TRX 地址
	GetTRXWallet(context.Context, *MemberReq) (*WalletResp, error)
	// 转账（支持 ERC20 / TRC20）
	TransferCrypto(context.Context, *TransferReq) (*TransferResp, error)
	// 预估手续费
	EstimateGas(context.Context, *EstimateGasReq) (*EstimateGasResp, error)
	// 获取对账钱包
	GetReconcileWallet(context.Context, *Empty) (*WalletResp, error)
	// 测试ETH转账
	TestTransferETH(context.Context, *TransferReq) (*TransferResp, error)
	// 测试TRON转账
	TestTransferTRON(context.Context, *TransferReq) (*TransferResp, error)
	// 查询余额
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	mustEmbedUnimplementedWalletServiceServer()
}

// UnimplementedWalletServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletServiceServer struct{}

func (UnimplementedWalletServiceServer) GetUniqueId(context.Context, *Empty) (*UniqueIdResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUniqueId not implemented")
}
func (UnimplementedWalletServiceServer) CreateUserWallet(context.Context, *CreateWalletReq) (*CreateWalletResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUserWallet not implemented")
}
func (UnimplementedWalletServiceServer) ListWallet(context.Context, *MemberReq) (*WalletListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWallet not implemented")
}
func (UnimplementedWalletServiceServer) GetETHWallet(context.Context, *MemberReq) (*WalletResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetETHWallet not implemented")
}
func (UnimplementedWalletServiceServer) GetTRXWallet(context.Context, *MemberReq) (*WalletResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTRXWallet not implemented")
}
func (UnimplementedWalletServiceServer) TransferCrypto(context.Context, *TransferReq) (*TransferResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferCrypto not implemented")
}
func (UnimplementedWalletServiceServer) EstimateGas(context.Context, *EstimateGasReq) (*EstimateGasResp, error) {
	return nil, status.Error(codes.Unimplemented, "method EstimateGas not implemented")
}
func (UnimplementedWalletServiceServer) GetReconcileWallet(context.Context, *Empty) (*WalletResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReconcileWallet not implemented")
}
func (UnimplementedWalletServiceServer) TestTransferETH(context.Context, *TransferReq) (*TransferResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TestTransferETH not implemented")
}
func (UnimplementedWalletServiceServer) TestTransferTRON(context.Context, *TransferReq) (*TransferResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TestTransferTRON not implemented")
}
func (UnimplementedWalletServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedWalletServiceServer) mustEmbedUnimplementedWalletServiceServer() {}
func (UnimplementedWalletServiceServer) testEmbeddedByValue()                       {}

// UnsafeWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServiceServer will
// result in compilation errors.
type UnsafeWalletServiceServer interface {
	mustEmbedUnimplementedWalletServiceServer()
}

func RegisterWalletServiceServer(s grpc.ServiceRegistrar, srv WalletServiceServer) {
	// If the following call panics, it indicates UnimplementedWalletServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletService_ServiceDesc, srv)
}

func _WalletService_GetUniqueId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetUniqueId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetUniqueId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetUniqueId(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_CreateUserWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).CreateUserWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_CreateUserWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).CreateUserWallet(ctx, req.(*CreateWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ListWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ListWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ListWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ListWallet(ctx, req.(*MemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetETHWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetETHWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetETHWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetETHWallet(ctx, req.(*MemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetTRXWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetTRXWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetTRXWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetTRXWallet(ctx, req.(*MemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_TransferCrypto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).TransferCrypto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_TransferCrypto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).TransferCrypto(ctx, req.(*TransferReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_EstimateGas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimateGasReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).EstimateGas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_EstimateGas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).EstimateGas(ctx, req.(*EstimateGasReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetReconcileWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetReconcileWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetReconcileWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetReconcileWallet(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_TestTransferETH_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).TestTransferETH(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_TestTransferETH_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).TestTransferETH(ctx, req.(*TransferReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_TestTransferTRON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).TestTransferTRON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_TestTransferTRON_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).TestTransferTRON(ctx, req.(*TransferReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletService_ServiceDesc is the grpc.ServiceDesc for WalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUniqueId",
			Handler:    _WalletService_GetUniqueId_Handler,
		},
		{
			MethodName: "CreateUserWallet",
			Handler:    _WalletService_CreateUserWallet_Handler,
		},
		{
			MethodName: "ListWallet",
			Handler:    _WalletService_ListWallet_Handler,
		},
		{
			MethodName: "GetETHWallet",
			Handler:    _WalletService_GetETHWallet_Handler,
		},
		{
			MethodName: "GetTRXWallet",
			Handler:    _WalletService_GetTRXWallet_Handler,
		},
		{
			MethodName: "TransferCrypto",
			Handler:    _WalletService_TransferCrypto_Handler,
		},
		{
			MethodName: "EstimateGas",
			Handler:    _WalletService_EstimateGas_Handler,
		},
		{
			MethodName: "GetReconcileWallet",
			Handler:    _WalletService_GetReconcileWallet_Handler,
		},
		{
			MethodName: "TestTransferETH",
			Handler:    _WalletService_TestTransferETH_Handler,
		},
		{
			MethodName: "TestTransferTRON",
			Handler:    _WalletService_TestTransferTRON_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _WalletService_GetBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/wallet.proto",
}
