app:
  env: prod
  log_level: info
  http_port: ":9014"   # 应用自身的HTTP/Gin监听端口

mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: "123456"  # 加密后的密码，可在程序解密
  database: testdb
  charset: utf8mb4
  max_idle_conns: 20
  max_open_conns: 200
  conn_max_lifetime: 3600 # 秒

redis:
  addr: 127.0.0.1:6379
  password: "hanxing"
  db: 0
  pool_size: 50
  min_idle_conns: 10
grpcs:
  port: ":50051"           # gRPC监听端口
  enable_tls: false        # 是否启用TLS
  tls_cert: ""             # TLS证书路径，可选
  tls_key: ""              # TLS私钥路径，可选
tron:
  network: nile
  fullnode: https://nile.trongrid.io
  soliditynode: https://nile.trongrid.io
  eventserver: https://nile.trongrid.io
  usdt_contract: TXYZopYRdj2D9XRtbG411XZZ3kM5VkAeBf   # Nile USDT
  tron_http: https://nile.trongrid.io
  tron_url: grpc.nile.trongrid.io:50051
  tron_api_key:
    - 47068565-4b08-47c3-b3cd-d5e96b7df666
    - 4158df7e-4c51-491f-ad19-ef2950f48eef
    - ee774953-07f8-4f87-b30c-8a10febdf966

